[package]
name = "validator"
version.workspace = true
edition.workspace = true

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tucana = { workspace = true }
